### ISSUE TITLE
Using Directus as a Baby Health Tracker

### ISSUE THREAD

**Issue by amo42** [directus-labs/guest-authoring#11]
### What is your idea?

As already published here: https://discord.com/channels/725371605378924594/1072890184250691704

I'd set up Directus to track some health data. Within the blog post I'd like to fully describe how this was made, give more detailes and screenshots about the collections, flows, insights and 3rd party integrations I've configured. 

Basically, Directus is uses as a backend to store, evaluate and perfome actions based on health data coming from a health tracker for newborns and toddlers. 

### What are the key takeaways from your post?

As I'm using more or less every feature from stock Directus the article would be super helpful for

- beginners to get into a more complex project without coding knowledge (some JS could be helpful) 
- learn how to integrate Directus into 3rd party tools using Flows by consuming REST apis
- get to know with Collections, Flows and Insights
- Integrate all of this Directus modules into a single project

### What type of post is this?

Full Project Build with Directus

### Country of residence

Germany

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice to us once the final draft of your work is completed.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
This looks good and, knowing what the project looks like, I'm excited to have this put together. 

You've given four key takeaways - I would suggest focusing more on the first two as that's more novel. The other two can absolutely be mentioned, but I wouldn't feel the need to explain these in much detail.

When do you think you could have it done by? We can pay $350 for this post. 😄

**Comment by phazonoverload** [comment]
Hey @amo42 it's been a while since this one first came up and was approved. Can I get a indication of if you're still working on it or whether you're no longer interested? 

If you're up for it - can I get an indication of when you might have a first draft done?

**Comment by amo42** [comment]
Hey @phazonoverload thanks for the ping. I'm still highly interested into writing the article. I've already started with with a rought agenda but as we have changed the hardware (the health tracker) I'm currently about to rewrite all the flows I need to access the data.

Should we aim for end of January/beginning of February where I hand in the first draft for a review on your side? 

Cheers 
Andreas

**Comment by phazonoverload** [comment]
Yeah that timing works for me

**Comment by phazonoverload** [comment]
Just wanted to share that we've recently updated our process for guest authoring to have deadlines for first drafts so we can better plan content.

The deadline for first draft is February 2 😄 In future, we'll agree this ahead of time, but it's aligned what what we have agreed off-platform.

**Comment by phazonoverload** [comment]
Hey @amo42 this has been a post in the works for a long time. I'm going to need to place an absolute deadline for the first draft of this Sunday, so I can review on Monday. If you're not able to do it that's ok but I need to resolve this so it's not hanging in terms of scheduling and budgeting.
