### ISSUE TITLE
Build a Personal Tracking Application with Vue.js and Directus

### ISSUE THREAD

**Issue by uma-victor1** [directus-labs/guest-authoring#162]
### What is your idea?

The reader of this article will gain practical experience in setting up Vue.js for frontend development with Directus as a backend CMS. They'll learn to architect and manage a Directus CMS, implement user interfaces with Vue.js, and connect these interfaces to Directus securely and efficiently.

### What are the key takeaways from your post?

- Introduction to Vue.js and Directus
- Setting up the development environment
- Designing the database schema in Directus
- Building the backend with Directus
- Developing the frontend with Vue.js
- Integrating some personal tracking features
- Conclusion

### What type of post is this?

Full Project Build with Directus

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671) or a PayPal account.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
Thank you for submitting this idea, but unfortunately we are not accepting it as part of our guest author program. Please feel free to submit additional ideas in future.
