### ISSUE TITLE
Build A GitHub Repository Tracker Chrome Extension With Directus

### ISSUE THREAD

**Issue by psalmuelle** [directus-labs/guest-authoring#173]
### What is your idea?

The idea is to build an extension to track Github repositories and receive notifications for updates using Github API and Directus/Directus Flow. 
Users can input the GitHub repository they want to track. The extension then displays information and the current status of the repository ( e.g open issues, pull requests, commits). Users can keep track of multiple repositories and receive notifications when updates occur on a tracked repository.

I will use Directus to store their basic info, their tracked repo and Directus flow to implement getting info in real time from github API.

### What are the key takeaways from your post?

The takeaway is to inform users of the possibilities of Directus in building apps. They also get to know how to build a chrome extension.

### What type of post is this?

Extension-Building Guide

### Country of residence

Nigeria

### Terms & Conditions

- [X] You understand that submitting this form does not mean we accept your proposal. We will accept proposals at our discretion.
- [X] You understand that to be paid you will need to generate an invoice with a 30 day payment term and send it to us once the final draft of your work is accepted (we will share how to do this once finished).
- [X] You understand that you will require either a bank account in one of the countries listed here (https://help.bill.com/direct/s/article/360007172671) or a PayPal account.
- [X] You understand that you will grant us an unlimited license to post and promote your work as part of this program. You may repost, but using our copy as the canonical source.
- [X] You are aged 18 or over.

**Comment by phazonoverload** [comment]
The idea of tracking changes in a GitHub repo is interesting, but applying it in a Chrome Extension is not. Would you be open to just focusing on repo tracking over time and alerts via Flows?

**Comment by psalmuelle** [comment]
Yes! That would be fine. 
The topic would be 'Build A GitHub Repository Tracker With Directus Flow'

**Comment by phazonoverload** [comment]
Based on the agreed scope we can pay $250 for this post.

This post will be included as part of our July content schedule. The first draft is due on June 24 so we have time to properly review it and you have time to respond.

If interested and you’re happy to commit to the deadline, please let me know in the next few days and I will mark this issue as Approved.

The process is detailed in the README of this repo 😄

**Comment by psalmuelle** [comment]
I am very much interested in working on this article. 

Thank you @phaonoverload
